create table sms_table(
    CDR_ID          bigint null,
    CDR_SUB_ID      bigint null,
    CDR_TYPE        varchar null,
    SPLIT_CDR_REASON varchar null,
    CDR_BATCH_ID     bigint null,
    SRC_REC_LINE_NO  bigint null,
    SRC_CDR_ID       bigint null,
    SRC_CDR_NO       bigint null,
    STATUS           varchar null,
    RE_RATING_TIMES  bigint null,
    CREATE_DATE      date null ,
    START_DATE       date null,
    END_DATE         date,
    CUST_LOCAL_START_DATE date null,
    CUST_LOCAL_END_DATE  date null,
    STD_EVT_TYPE_ID   bigint null,
    EVT_SOURCE_CATEGORY varchar null,
    OBJ_TYPE           varchar null,
    OBJ_ID            bigint null,
    OWNER_CUST_ID     bigint null,
    DEFAULT_ACCT_ID   bigint null,
    PRI_IDENTITY      varchar null,
    BILL_CYCLE_ID     varchar null,
    SERVICE_CATEGORY  varchar null,
    USAGE_SERVICE_TYPE varchar null,
    SESSION_ID         varchar null,
    RESULT_CODE        bigint null,
    RESULT_REASON      varchar null,
    BE_ID              bigint null,
    HOT_SEQ            bigint null,
    CP_ID              bigint null,
    RECEPIENT_NUMBER   varchar null,
    USAGE_MEASURE_ID   bigint null,
    ACTUAL_USAGE       bigint null,
    RATE_USAGE         bigint null,
    SERVICE_UNIT_TYPE  bigint null,
    USAGE_MEASURE_ID2  bigint null,
    ACTUAL_USAGE2      bigint null,
    RATE_USAGE2        bigint null,
    SERVICE_UNIT_TYPE2 bigint null,
    DEBIT_AMOUNT         bigint null,
    Reserved             bigint null,
    DEBIT_FROM_PREPAID   bigint null,
    DEBIT_FROM_ADVANCE_PREPAID bigint null,
    DEBIT_FROM_POSTPAID bigint null,
    DEBIT_FROM_ADVANCE_POSTPAID bigint null,
    DEBIT_FROM_CREDIT_POSTPAID bigint null,
    TOTAL_TAX            bigint null,
    FREE_UNIT_AMOUNT_OF_TIMES bigint null,
    FREE_UNIT_AMOUNT_OF_DURATION bigint null,
    FREE_UNIT_AMOUNT_OF_FLUX bigint null,
    ACCT_ID              bigint null,
    ACCT_BALANCE_ID      bigint null,
    BALANCE_TYPE         bigint null,
    CUR_BALANCE          bigint null,
    CHG_BALANCE          bigint null,
    CURRENCY_ID          bigint null,
    OPER_TYPE          bigint null,
    CUR_EXPIRE_TIME    date null,
    FU_OWN_TYPE         varchar null,
    FU_OWN_ID           bigint null,
    FREE_UNIT_TYPE      bigint null,
    FREE_UNIT_ID        bigint null,
    BONUS_AMOUNT        bigint null,
    CURRENT_AMOUNT      bigint null,
    FU_MEASURE_ID       bigint null,
   callingpartynumber varchar (64) not null,
   calledpartynumber varchar (64) not null,
   callingpartyimsi varchar (64)  null,
   calledpartyimsi varchar (64)  null,
   dialednumber varchar (64)  null,
   originalcalledparty  varchar (64)  null,
   serviceflow varchar (41) not null,
   callforwardindicator varchar (21) not null,
   callingroaminfo varchar (20) null,
   callingcellid varchar (20) null,
   calledroaminfo varchar (20) null,
   calledcellid varchar (20) null,
   timestampofssp varchar (14) null,
   timezoneofssp varchar (10) null,
   bearercapability varchar (32) null,
   chargingtime varchar (14) not null,
   sendresult varchar (10) default 0,
   smsid varchar (63) not null,
   imei varchar (24) null,
   smlength varchar (10) null,
   smscaddress varchar (20) null,
   refundindicator varchar (20)  default 0,
   brandid varchar (20)  default 0,
   mainofferingid varchar (20)  default 0,
   chargingpartyvarchar varchar (64) not null,
   chargepartyindicator varchar (1) not null,
   paytype varchar (1) not null,
   chargingtype  varchar (1) not null,
   smstype varchar (10) not null,
   onnetindicator varchar  (1) not null,
   roamstate varchar  (1) not null,
   callinghomecountrycode varchar (10) null,
   callinghomeareavarchar varchar (10) null,
   callinghomenetworkcode varchar (10) null,
   callingroamcountrycode varchar (10) null,
   callingroamareavarchar varchar (10) null,
   callingroamnetworkcode varchar (10) null,
   calledhomecountrycode varchar (10) null,
   calledhomeareavarchar varchar (10) null,
   calledhomenetworkcode varchar (10) null,
   calledroamcountrycode varchar (10) null,
   calledroamareavarchar varchar (10) null,
   calledroamnetworkcode varchar (10) null,
   servicetype varchar (128) null,
   specialvarcharindicator varchar (10) default 0,
   npflag varchar (1) default 0,
   npprefix varchar (6) null,
   callingcugno varchar (20) default 0,
   calledcugno varchar (20) default 0,
   opposenetworktype varchar (10) null,
   opposevarchartype varchar (10) not null,
   CallingNetworkType varchar null,
   CalledNetworkType varchar null,
   CallingVPNTopGroupNumber varchar null,
   CallingVPNGroupNumber varchar null,
   CallingVPNShortNumber varchar null,
   CalledVPNTopGroupNumber varchar null,
   CalledVPNGroupNumber varchar null,
   CalledVPNShortNumber varchar null,
   GroupCallType varchar null,
   OnlineChargingFlag varchar not null,
   StartTimeOfBillCycle varchar null,
   LastEffectOffering bigint default (0),
   DTDiscount bigint  default (0),
   OpposeMainOfferingID  bigint  default (0),
   HomeZoneID bigint  default (0),
   SpecialZoneID bigint  default (0),
   MainBalanceInfo varchar (255) null,
   ChgBalanceInfo varchar (255) null,
   ChgFreeUnitInfo varchar (255) null,
   UserState varchar (10) null,
   GroupPayFlag bigint  null,
   RoamingZoneID varchar(20) null,
   PrimaryOfferChgAmt bigint default (0),
   Reserved2 bigint  null,
   RECEPIENT_CP_ID varchar(5) null,
   TaxInfo varchar(255) null,
   VistLocalStartTime varchar(14) null,
   VistLocalEndTime  varchar(14) null,
   SUBSCRIBER_KEY varchar(64) null,
   ACCOUNT_KEY varchar(64) null,
   OWNER_CUST_CODE varchar(32) null,
   SameBrandFlag bigint null,
   TADIGCode  varchar(5) null,
   DiscountOfLastEffOffering bigint null,
   Unround DOUBLE PRECISION null,
   TapFileName varchar(64) null,
   PREPAID_BALANCE bigint null,
   POSTPAID_BALANCE bigint null,
   PAY_PAYTYPE bigint null,
   PAY_BILL_CYCLE_ID varchar(20) null,
   PAY_FREE_UNIT_AMOUNT_OF_TIMES bigint null,
   PAY_DEBIT_FROM_PREPAID bigint null,
   PAY_PREPAID_BALANCE bigint null,
   PAY_ACCOUNT_KEY varchar(64) null,
   PAY_DEBIT_FROM_POSTPAID bigint null,
   PAY_POSTPAID_BALANCE bigint null,
   PAY_DEFAULT_ACCT_ID bigint null,
   PAY_CUST_ID bigint null,
   PAY_CUST_CODE varchar(32) null,
   EntireAmount bigint null,
   accumulationchange varchar(256) null,
   AcctBalChgList varchar(512) null,
   CHARGE_OF_FUND_AMOUNT bigint null,
   PAY_CHARGE_OF_FUND_AMOUNT bigint null,
   PAY_SUB_ID bigint null,
   RATED_OFFER_ID varchar(512) null,
   OverDraftFlag bigint  default (0)
);